name: Android APK Build (NDK r28c + 16K Alignment)

on:
  workflow_dispatch:  # 手动触发
  push:               # 推送时触发
    branches: [ main ]
    paths:
      - '**.py'
      - '**.kv'
      - 'buildozer.spec'
      - '.github/workflows/**'

env:
  NDK_VERSION: "28c"
  NDK_FULL_VERSION: "28.2.13676358"
  ANDROID_API: 31
  MIN_API: 21
  BUILD_TOOLS: "34.0.0"
  PYTHON_VERSION: "3.9"

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: '${{ env.PYTHON_VERSION }}'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget unzip openjdk-17-jdk \
          autoconf automake libtool \
          libffi-dev libssl-dev git make p7zip-full curl \
          zlib1g-dev

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install --upgrade buildozer
        pip install --upgrade Cython==0.29.36

    - name: Verify and update buildozer.spec
      run: |
        if [ ! -f "buildozer.spec" ]; then
          buildozer init
          echo "Created new buildozer.spec"
        fi

        # 更新 NDK 配置
        if grep -q "android.ndk" buildozer.spec; then
          sed -i "s|android.ndk =.*|android.ndk = ${{ env.NDK_VERSION }}|" buildozer.spec
        else
          echo "android.ndk = ${{ env.NDK_VERSION }}" >> buildozer.spec
        fi

        # 确保 16K 对齐参数存在
        if ! grep -q "android.extra_ldflags" buildozer.spec; then
          echo 'android.extra_ldflags = -Wl,-z,max-page-size=16384,-z,common-page-size=16384' >> buildozer.spec
        fi

        echo "Final buildozer.spec settings:"
        grep -E "(android.ndk|android.extra_ldflags)" buildozer.spec || true

    - name: Download Android NDK
      run: |
        NDK_CACHE_PATH="$HOME/.buildozer/android/packages"
        mkdir -p $NDK_CACHE_PATH
        NDK_URL="https://dl.google.com/android/repository/android-ndk-r${{ env.NDK_VERSION }}-linux.zip"
        NDK_ZIP_PATH="$NDK_CACHE_PATH/ndk.zip"

        echo "Downloading NDK from $NDK_URL"
        curl -L --progress-bar -o "$NDK_ZIP_PATH" "$NDK_URL"
        unzip -q "$NDK_ZIP_PATH" -d "$NDK_CACHE_PATH"
        echo "NDK_PATH=$NDK_CACHE_PATH/android-ndk-r${{ env.NDK_VERSION }}" >> $GITHUB_ENV

    - name: Build with Buildozer
      run: |
        export ANDROID_NDK_HOME="$HOME/.buildozer/android/packages/android-ndk-r${{ env.NDK_VERSION }}"
        export PATH="$ANDROID_NDK_HOME:$PATH"
        buildozer -v android debug

    - name: Verify build output
      id: verify_apk
      run: |
        if ls bin/*.apk 1> /dev/null 2>&1; then
          APK_FILE=$(ls bin/*.apk | head -1)
          echo "APK_PATH=$APK_FILE" >> $GITHUB_ENV
          echo "Found APK: $APK_FILE"
        else
          echo "No APK file found!"
          exit 1
        fi

    - name: Verify .so page alignment
      run: |
        unzip -o "${{ env.APK_PATH }}" -d apk_unpacked >/dev/null
        echo "Checking ELF page sizes inside APK..."
        find apk_unpacked -name "*.so" | while read sofile; do
          echo "---- $sofile ----"
          readelf -l "$sofile" | grep 'Page size'
        done

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: ${{ env.APK_PATH }}
        retention-days: 7

    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: .
        if-no-files-found: ignore
        retention-days: 7

    - name: Fallback - Direct p4a build
      if: failure()
      run: |
        export ANDROID_NDK_HOME="$HOME/.buildozer/android/packages/android-ndk-r${{ env.NDK_VERSION }}"
        export PATH="$ANDROID_NDK_HOME:$PATH"
        pip install python-for-android
        python -m pythonforandroid.toolchain apk \
          --dist_name myapp \
          --bootstrap sdl2 \
          --requirements python3,kivy \
          --arch arm64-v8a \
          --ndk-path "$ANDROID_NDK_HOME" \
          --debug
