name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Buildozer and dependencies
      run: |
        sudo apt-get update
        # 安装所有必要的构建工具
        sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev 
        sudo apt-get install -y libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        sudo apt-get install -y automake m4
        pip install buildozer Cython==0.29.33 virtualenv

    # 修复1: 手动下载并验证NDK
    - name: Setup Android NDK
      run: |
        # 创建缓存目录
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        
        # 下载NDK (使用r23b版本，更稳定)
        NDK_VERSION="r23b"
        NDK_FILE="android-ndk-${NDK_VERSION}-linux.zip"
        wget --tries=3 --waitretry=30 --retry-connrefused "https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux.zip" -O $NDK_FILE
        
        # 验证下载完整性
        if [ ! -f "$NDK_FILE" ]; then
          echo "❌ NDK下载失败"
          exit 1
        fi
        
        # 解压NDK
        unzip -q $NDK_FILE
        rm $NDK_FILE
        
        # 设置环境变量
        echo "ANDROID_NDK_HOME=$(pwd)/android-ndk-${NDK_VERSION}" >> $GITHUB_ENV
        echo "NDK目录设置完成: $(pwd)/android-ndk-${NDK_VERSION}"

    # 修复2: 更新autotools配置
    - name: Update autotools configuration
      run: |
        # 进入你的应用目录
        cd testapps/your_app_name
        
        # 查找并更新所有configure.ac文件
        find . -name 'configure.ac' -execdir sh -c '
          echo "处理目录: $(pwd)"
          # 备份原始文件
          cp configure.ac configure.ac.bak
          
          # 运行autoupdate
          autoupdate || echo "autoupdate可能已更新文件"
          
          # 重新生成配置
          autoreconf -vif
        ' \;

    - name: Build the APK
      run: |
        cd testapps/your_app_name
        # 设置Buildozer使用我们下载的NDK
        export ANDROID_NDK_HOME="$HOME/.buildozer/android/platform/android-ndk-r23b"
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-app-apk
        path: testapps/your_app_name/bin/*.apk
