name: Android APK Build (Stable - NDK r28c)

on:
  workflow_dispatch:  # 允许手动触发工作流
  push:               # 推送代码时自动触发
    branches: [ main ]
    paths:            # 仅当相关文件更改时触发
      - '**.py'
      - '**.kv'
      - 'buildozer.spec'
      - '.github/workflows/**'

env:
  NDK_VERSION: "28c"           # NDK 版本简称 (用于下载URL)
  NDK_FULL_VERSION: "28.2.13676358" # NDK 完整版本号 (用于buildozer.spec配置)
  ANDROID_API: 31
  MIN_API: 21
  BUILD_TOOLS: "34.0.0"
  PYTHON_VERSION: "3.9"        # 使用兼容性好的Python 3.9

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 60         # 设置超时防止无限挂起

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 检出代码[4,5](@ref)

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: '${{ env.PYTHON_VERSION }}'  # 设置Python版本[7](@ref)

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget unzip openjdk-17-jdk \
          autoconf automake libtool \
          libffi-dev libssl-dev git make p7zip-full  # 安装系统依赖[1](@ref)

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install --upgrade buildozer
        pip install --upgrade Cython==0.29.36  # 安装Buildozer和固定版本的Cython[1](@ref)

    - name: Conditional Buildozer Initialization
      run: |
        if [ ! -f "buildozer.spec" ]; then
          buildozer init
          echo "Buildozer initialized successfully"
        else
          echo "buildozer.spec already exists, checking configuration..."
          # 确保spec文件中的NDK版本配置正确
          if grep -q "android.ndk" buildozer.spec; then
            sed -i "s|android.ndk =.*|android.ndk = ${{ env.NDK_FULL_VERSION }}|" buildozer.spec
            echo "Updated buildozer.spec to use NDK ${{ env.NDK_FULL_VERSION }}"
          else
            echo "android.ndk = ${{ env.NDK_FULL_VERSION }}" >> buildozer.spec
            echo "Added NDK configuration to buildozer.spec"
          fi
        fi

    - name: Download Android NDK (Official Source with Enhanced Retry)
      run: |
        NDK_CACHE_PATH="$HOME/.buildozer/android/packages"
        mkdir -p $NDK_CACHE_PATH
        
        # 使用官方下载URL格式[1](@ref)
        NDK_URL="https://dl.google.com/android/repository/android-ndk-r${{ env.NDK_VERSION }}-linux.zip"
        NDK_ZIP_PATH="$NDK_CACHE_PATH/ndk.zip"
        
        echo "Downloading from official source: $NDK_URL"
        
        # 增强的重试机制（最多5次尝试）
        MAX_ATTEMPTS=5
        for ((attempt=1; attempt<=$MAX_ATTEMPTS; attempt++)); do
          echo "Attempt $attempt/$MAX_ATTEMPTS: Downloading NDK..."
          
          # 使用wget下载，显示进度，设置超时和重试
          if wget --progress=bar:force --tries=3 --timeout=120 -O "$NDK_ZIP_PATH" "$NDK_URL"; then
            echo "Download completed. Verifying file integrity..."
            
            # 验证ZIP文件完整性
            if unzip -tq "$NDK_ZIP_PATH" &>/dev/null; then
              echo "ZIP file integrity verified. Extracting..."
              
              # 解压NDK
              unzip -q "$NDK_ZIP_PATH" -d "$NDK_CACHE_PATH"
              
              # 验证解压后的目录
              if [ -d "$NDK_CACHE_PATH/android-ndk-r${{ env.NDK_VERSION }}" ]; then
                echo "NDK ${{ env.NDK_VERSION }} successfully installed!"
                echo "NDK_PATH=$NDK_CACHE_PATH/android-ndk-r${{ env.NDK_VERSION }}" >> $GITHUB_ENV
                break
              else
                echo "Error: Extraction succeeded but directory not found!"
              fi
            else
              echo "Error: Downloaded ZIP file is corrupted or incomplete!"
              rm -f "$NDK_ZIP_PATH"
            fi
          else
            echo "Download attempt $attempt failed."
            rm -f "$NDK_ZIP_PATH"
          fi
          
          # 如果不是最后一次尝试，等待后重试
          if [ $attempt -lt $MAX_ATTEMPTS ]; then
            echo "Waiting 30 seconds before next attempt..."
            sleep 30
          else
            echo "Error: All $MAX_ATTEMPTS download attempts failed!"
            echo "Please check:"
            echo "1. The official NDK URL: $NDK_URL"
            echo "2. Network connectivity to dl.google.com"
            exit 1
          fi
        done

    - name: Build with Buildozer
      run: |
        # 设置环境变量
        export ANDROID_NDK_HOME="$HOME/.buildozer/android/packages/android-ndk-r${{ env.NDK_VERSION }}"
        export PATH="$ANDROID_NDK_HOME:$PATH"
        
        echo "Using NDK path: $ANDROID_NDK_HOME"
        echo "NDK contents:"
        ls "$ANDROID_NDK_HOME" | head -10
        
        # 执行构建并捕获输出到日志文件[1](@ref)
        buildozer -v android debug 2>&1 | tee build_output.log

    - name: Verify build output
      run: |
        if ls bin/*.apk 1> /dev/null 2>&1; then
          APK_FILE=$(ls bin/*.apk | head -1)
          echo "Build successful! APK file: $APK_FILE"
          echo "File size: $(du -h "$APK_FILE" | cut -f1)"
        else
          echo "Error: No APK file found in bin/ directory!"
          echo "Contents of bin/:"
          ls -la bin/ || true
          exit 1
        fi

    - name: Prepare logs for upload
      if: always()  # 即使构建失败也执行
      run: |
        mkdir -p artifacts_logs
        # 收集所有可能的日志文件
        find . -name "*.log" -exec cp {} artifacts_logs/ \; 2>/dev/null || true
        # 复制buildozer.spec用于调试
        cp buildozer.spec artifacts_logs/ || true
        echo "Logs prepared for upload:"
        ls -la artifacts_logs/ || true

    - name: Upload APK artifact
      if: success()  # 只有构建成功时才上传APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk-${{ github.run_number }}
        path: bin/*.apk
        retention-days: 7

    - name: Upload build logs
      if: always()  # 即使构建失败也上传日志
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-${{ github.run_number }}
        path: artifacts_logs/
        if-no-files-found: ignore  # 如果没有文件也不报错[3](@ref)
