name: Android APK Build with NDK r28c

on: [workflow_dispatch, push]

env:
  NDK_VERSION: "28c"           # 用于下载
  NDK_FULL_VERSION: "28.2.13676358" # 用于buildozer.spec

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip openjdk-17-jdk

    - name: Install Buildozer
      run: pip install buildozer

    - name: Ensure NDK configuration in buildozer.spec
      run: |
        # 确保使用NDK r28c的完整版本号
        if grep -q "android.ndk" buildozer.spec; then
          sed -i "s|android.ndk =.*|android.ndk = ${{ env.NDK_FULL_VERSION }}|" buildozer.spec
        else
          echo "android.ndk = ${{ env.NDK_FULL_VERSION }}" >> buildozer.spec
        fi
        
        # 添加16K对齐标志
        if ! grep -q "android.extra_ldflags" buildozer.spec; then
          echo 'android.extra_ldflags = -Wl,-z,max-page-size=16384,-z,common-page-size=16384' >> buildozer.spec
        fi

    - name: Build with Buildozer
      run: |
        buildozer android debug

    - name: Check for APK
      run: |
        if ls bin/*.apk 1> /dev/null 2>&1; then
          echo "Build successful!"
          ls -la bin/*.apk
        else
          echo "Build failed - no APK found"
          exit 1
        fi
