name: Android APK Builder with API 31

on:
  workflow_dispatch:  # 允许手动触发
  push:               # 推送代码时自动触发
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: 设置 Android NDK (使用镜像)
      run: |
    NDK_URL="https://repo.huaweicloud.com/android/repository/android-ndk-r28c-linux.zip" # 使用镜像
    NDK_CACHE_PATH="$HOME/.buildozer/android/packages/ndk/"
    mkdir -p $NDK_CACHE_PATH
    wget --tries=3 --timeout=60 -O $NDK_CACHE_PATH/android-ndk-r28c-linux.zip $NDK_URL || exit 1
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zip unzip openjdk-17-jdk \
          autoconf automake libtool \
          libffi-dev libssl-dev git wget make

    - name: Install Buildozer and Cython
      run: pip install buildozer Cython==0.29.33

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
